export const TOGGLE_NAVIGATION = "TOGGLE_NAVIGATION";

export const SEARCH_CLIENTS = "SEARCH_CLIENTS";
export const FETCH_CLIENTS = "FETCH_CLIENTS";
export const FETCH_CLIENT = "FETCH_CLIENT";
export const CREATE_CLIENT = "CREATE_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";

export const SEARCH_JOBS = "SEARCH_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";
export const FETCH_JOB = "FETCH_JOB";
export const CREATE_JOB = "CREATE_JOB";
export const EDIT_JOB = "EDIT_JOB";
export const DELETE_JOB = "DELETE_JOB";

export const FETCH_CLIENT_OPTIONS = "FETCH_CLIENT_OPTIONS";
export const FETCH_STAFF_OPTIONS = "FETCH_STAFF";
export const FETCH_JOB_STATUS_OPTIONS = "FETCH_JOB_STATUS_OPTIONS";
export const FETCH_HOURS_TYPE_OPTIONS = "FETCH_HOURS_TYPE_OPTIONS";
